# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Install chrome
        uses: browser-actions/setup-chrome@v1
      - name: Test chrome
        run: chrome --version
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
