# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Install chrome
        run: docker pull alpeware/chrome-headless-trunk && docker run -d -p 9477:9222 alpeware/chrome-headless-trunk
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"
